"""character_module_id_nullable

Revision ID: 53e23cb587bd
Revises: 6ad0ae3e87d8
Create Date: 2026-06-26 10:39:51.260899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e23cb587bd'
down_revision: Union[str, Sequence[str], None] = '6ad0ae3e87d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
