"""初始化数据库模型

Revision ID: 6ad0ae3e87d8
Revises: 
Create Date: 2026-06-25 20:23:52.410172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad0ae3e87d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rule_system', sa.Enum('coc', 'dnd', name='rule_system'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('world_setting', sa.JSON(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('scenes', sa.JSON(), nullable=False),
    sa.Column('npcs', sa.JSON(), nullable=False),
    sa.Column('maps', sa.JSON(), nullable=False),
    sa.Column('clues', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('rule_system', sa.Enum('coc', 'dnd', name='rule_system'), nullable=False),
    sa.Column('is_player', sa.Boolean(), nullable=False),
    sa.Column('base_attributes', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('system_data', sa.JSON(), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'dead', 'incapacitated', name='character_status'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('setup', 'active', 'paused', 'ended', name='session_status'), nullable=False),
    sa.Column('player_character_id', sa.String(), nullable=True),
    sa.Column('current_scene_id', sa.String(), nullable=True),
    sa.Column('world_state', sa.JSON(), nullable=False),
    sa.Column('turn_state', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['player_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('dialogue', 'action', 'dice', 'narration', 'system', name='event_type'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_session_id'), 'event_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_session_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('game_sessions')
    op.drop_table('characters')
    op.drop_table('modules')
    # ### end Alembic commands ###
